### ISSUE TITLE
cant find scDREAMER.yaml

### ISSUE THREAD

**Issue by Rohit-Satyam** [Zafar-Lab/scDREAMER#1]
This file for environment setup is missing `scDREAMER.yaml`. Kindly add it.

**Comment by Rohit-Satyam** [comment]
I tried this as well and I get the following error:
```
python setup.py install
Traceback (most recent call last):
  File "/home/subudhak/miniconda3/envs/scdreamer/lib/python3.6/site-packages/setuptools/_vendor/packaging/specifiers.py", line 677, in __init__
    parsed.add(Specifier(specifier))
  File "/home/subudhak/miniconda3/envs/scdreamer/lib/python3.6/site-packages/setuptools/_vendor/packaging/specifiers.py", line 112, in __init__
    raise InvalidSpecifier("Invalid specifier: '{0}'".format(spec))
setuptools.extern.packaging.specifiers.InvalidSpecifier: Invalid specifier: '3.6'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    'Programming Language :: Python :: 3.7'
  File "/home/subudhak/miniconda3/envs/scdreamer/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/subudhak/miniconda3/envs/scdreamer/lib/python3.6/distutils/core.py", line 121, in setup
    dist.parse_config_files()
  File "/home/subudhak/miniconda3/envs/scdreamer/lib/python3.6/site-packages/setuptools/dist.py", line 799, in parse_config_files
    self, self.command_options, ignore_option_errors=ignore_option_errors
  File "/home/subudhak/miniconda3/envs/scdreamer/lib/python3.6/site-packages/setuptools/config.py", line 150, in parse_configuration
    options.parse()
  File "/home/subudhak/miniconda3/envs/scdreamer/lib/python3.6/site-packages/setuptools/config.py", line 498, in parse
    section_parser_method(section_options)
  File "/home/subudhak/miniconda3/envs/scdreamer/lib/python3.6/site-packages/setuptools/config.py", line 469, in parse_section
    self[name] = value
  File "/home/subudhak/miniconda3/envs/scdreamer/lib/python3.6/site-packages/setuptools/config.py", line 222, in __setitem__
    value = parser(value)
  File "/home/subudhak/miniconda3/envs/scdreamer/lib/python3.6/site-packages/setuptools/_vendor/packaging/specifiers.py", line 679, in __init__
    parsed.add(LegacySpecifier(specifier))
  File "/home/subudhak/miniconda3/envs/scdreamer/lib/python3.6/site-packages/setuptools/_vendor/packaging/specifiers.py", line 112, in __init__
    raise InvalidSpecifier("Invalid specifier: '{0}'".format(spec))
setuptools.extern.packaging.specifiers.InvalidSpecifier: Invalid specifier: '3.6'
```

**Comment by Rohit-Satyam** [comment]
Saw an update in your repo and tried installing the dependencies and I got this error:

```
cd Environments/
mamba env create -f scDREAMER.yml
```
Error:
```
Pip subprocess error:
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-nw_sudn4/tensorrt-libs_936679de94bf4588b547eda30f62ece9/setup.py", line 137, in <module>
          raise RuntimeError(open("ERROR.txt", "r").read())
      RuntimeError:
      ###########################################################################################
      The package you are trying to install is only a placeholder project on PyPI.org repository.
      This package is hosted on NVIDIA Python Package Index.
      
      This package can be installed as:
      ```
      $ pip install --extra-index-url https://pypi.nvidia.com tensorrt-libs
      ```
      ###########################################################################################
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed

```

Besides kindly change the environment name as well `/home/subudhak/miniconda3/envs/tf2` from `tf2` to `scdreamer` in .yaml file [here](https://github.com/Zafar-Lab/scDREAMER/blob/e30800966ce68b9d38b86a1635a3115f3f253a9d/Environments/scDREAMER.yml#L250)

**Comment by Rohit-Satyam** [comment]
The yml I am posting [here](https://gist.github.com/Rohit-Satyam/0c0f290d99f1a4b8c084f4e816640500) worked for me without error. I added the following:

```
      - nvidia-pyindex
      - nvidia-tensorrt
      - --extra-index-url https://pypi.nvidia.com tensorrt-libs
```

The versions that got installed are 
```
nvidia-pyindex-1.0.9 nvidia-tensorrt-99.0.0 tensorrt-libs-8.6.1
```
and it would be wise to hardcode them unlike my .yml file since the tensorflow syntax keeps on changing.

**Comment by ajitashree** [comment]
Issue resolved

**Comment by ajitashree** [comment]
Thank you Rohit for the suggestion, made the recommended additions to .yml
